name:                netwarking
version:             0.1.0.0
github:              "githubuser/netwarking"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# synopsis:            Short description of your package
# category:            Web


description:         Please see the README on GitHub at <https://github.com/githubuser/netwarking#readme>

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: src

executables:
  netwarking-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - netwarking

tests:
  netwarking-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - netwarking
    - hspec

ghc-options:
  -XNamedFieldPuns
